version: "3.9"
services:
  prediction:
    build: .
    command: python app.py
    image: cifar-prediction-service:latest
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
    volumes:
      - ./src:/home/src/
      - ./resources:/home/resources/

  db_server:
    image: postgres:latest
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      - ./resources/db:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql